# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowConnSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowConnSetting(object):
    def setupUi(self, WindowConnSetting):
        WindowConnSetting.setObjectName("WindowConnSetting")
        WindowConnSetting.resize(350, 260)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/btn_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WindowConnSetting.setWindowIcon(icon)
        self.WidgetConnSetting = QtWidgets.QWidget(WindowConnSetting)
        self.WidgetConnSetting.setObjectName("WidgetConnSetting")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.WidgetConnSetting)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 102, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.LayoutConnLabel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.LayoutConnLabel.setContentsMargins(0, 0, 0, 0)
        self.LayoutConnLabel.setObjectName("LayoutConnLabel")
        self.LabelConnIpAddress = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.LabelConnIpAddress.setFont(font)
        self.LabelConnIpAddress.setObjectName("LabelConnIpAddress")
        self.LayoutConnLabel.addWidget(self.LabelConnIpAddress)
        self.LabelConnPort = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.LabelConnPort.setFont(font)
        self.LabelConnPort.setObjectName("LabelConnPort")
        self.LayoutConnLabel.addWidget(self.LabelConnPort)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.WidgetConnSetting)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 20, 221, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.LayoutConnEdit = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.LayoutConnEdit.setContentsMargins(0, 0, 0, 0)
        self.LayoutConnEdit.setObjectName("LayoutConnEdit")
        self.EditConnIpAddress = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.EditConnIpAddress.setFont(font)
        self.EditConnIpAddress.setText("")
        self.EditConnIpAddress.setObjectName("EditConnIpAddress")
        self.LayoutConnEdit.addWidget(self.EditConnIpAddress)
        self.EditConnPort = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.EditConnPort.setFont(font)
        self.EditConnPort.setText("")
        self.EditConnPort.setObjectName("EditConnPort")
        self.LayoutConnEdit.addWidget(self.EditConnPort)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.WidgetConnSetting)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 331, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.LayoutConnBtn = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.LayoutConnBtn.setContentsMargins(0, 0, 0, 0)
        self.LayoutConnBtn.setObjectName("LayoutConnBtn")
        self.BtnConnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.BtnConnSave.setFont(font)
        self.BtnConnSave.setObjectName("BtnConnSave")
        self.LayoutConnBtn.addWidget(self.BtnConnSave)
        self.BtnConnCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.BtnConnCancel.setFont(font)
        self.BtnConnCancel.setObjectName("BtnConnCancel")
        self.LayoutConnBtn.addWidget(self.BtnConnCancel)
        WindowConnSetting.setCentralWidget(self.WidgetConnSetting)

        self.retranslateUi(WindowConnSetting)
        QtCore.QMetaObject.connectSlotsByName(WindowConnSetting)

    def retranslateUi(self, WindowConnSetting):
        _translate = QtCore.QCoreApplication.translate
        WindowConnSetting.setWindowTitle(_translate("WindowConnSetting", "网络通讯参数设置"))
        self.LabelConnIpAddress.setText(_translate("WindowConnSetting", "IP地址："))
        self.LabelConnPort.setText(_translate("WindowConnSetting", "端   口："))
        self.BtnConnSave.setText(_translate("WindowConnSetting", "保存"))
        self.BtnConnCancel.setText(_translate("WindowConnSetting", "取消"))
